apiVersion: v1
kind: Pod
metadata:
  name: pod-env
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: ENV_KEY_1
      valueFrom:
        configMapKeyRef:
          name: env-config
          key: key1
