apiVersion: v1
kind: Pod
metadata:
  name: pod-hostpath
spec:
  volumes:
  - name: hostpath-vol
    hostPath:
      path: /opt
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /host
      name: hostpath-vol
      readOnly: true
