apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-files
spec:
  volumes:
  - name: secret-vol
    secret: 
      secretName: db-credentials
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /secret
      name: secret-vol
